# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Today I Learned
email: me@patricklee.nyc
description: > # this means to ignore newlines until "baseurl:"
  Today I Learned is a concept where one keeps a log of interesting lessons
  learned every day across all aspects of life.  Use it for programming,
  factoids, news, recipes, etc.  We're always learning, why not keep a record?
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://patricklee.nyc" # the base hostname & protocol for your site
twitter_username: patleeman
github_username:  patleeman

# Build settings
markdown: kramdown
